Towards refactoring the api
zeeguu/python-wordstats pull request #9
Opened 2018-05-03 12:07 UTC by joelgrondman

refactoring of list to dict, several functions changed due to this change
quick load_from_cache class method added that automatically searched for db entry or local file for instantiating object

2018-05-07 13:40 UTC, mircealungu requested changes

2018-05-07 13:40 UTC, mircealungu commented on wordstats/cognate_db.py
> +class UnknownCognateInfo(object):
Uh. Is this really needed? It's not used anywhere.

2018-05-07 13:40 UTC, mircealungu commented on wordstats/cognate_db.py
> +        self.secondary = languageTo
i think we should keep a parallel structure between the word and the language. 
thus, either: 
- word_from  / language_from
- or word_primary / language_primary

2018-05-07 13:40 UTC, mircealungu commented on wordstats/cognate_db.py
> +    primary = Column(String(20), nullable =False, index = True)
same observations about naming as before

2018-05-07 13:40 UTC, mircealungu commented on wordstats/cognate_info.py
> +                if self.distance_computer.edit_distance(w1, w2):
the naming here must be improved. 
`if edit_distance(w1, w2)` does not read like a condition. 

either `if edit_distance(w1,w2) < SOMETHING` or maybe, `if very_close_distance(w1, w2):` or something else that is better than `very_close_distance` but in the same vein.

2018-05-07 13:40 UTC, mircealungu commented on wordstats/cognate_info.py
> +                        self.candidates[w1] = [w2]
there are two more `pythonic` ways of doing this: 

see: https://stackoverflow.com/a/17756005/1200070

2018-05-07 13:40 UTC, mircealungu commented on wordstats/cognate_info.py
> +        Loads cognate information given the cognate code (e.g. ennl) and method_name
comment about cognate code is out of date.

2018-05-07 13:40 UTC, mircealungu commented on wordstats/cognate_info.py
> +        worth a rename of the method name
what's this "worth a rename" comment?

2018-05-07 13:40 UTC, mircealungu commented on wordstats/cognate_user_evaluation.py
> +                (key not in cognateinfo.whitelist.keys() or value not in cognateinfo.whitelist[key]):
can we move this complicated expression to it's own function? 
what i'd like a lot would be something like: `cognate.info.is_already_evaluated(key)`,
the fact that these two lines of code use four times cognateinfo should be a hint 
that this behavior belongs to that class.

2018-05-07 13:47 UTC, mircealungu requested changes

2018-05-07 13:47 UTC, mircealungu commented on wordstats/edit_distance.py
> +    def __init__(self, primary_language, secondary_language):
short comment on what is the meaning of this class would be good. 
also, i see no language awareness in the class. why?

2018-05-07 13:47 UTC, mircealungu commented on wordstats/edit_distance_function_factory.py
> +        self.languageTo = secondary_language
here we talk about languageFrom and languageTo. 
in the other class we had primary and secondary.
we should choose *one* convention, and use it all throughout the project.

2018-05-07 13:47 UTC, mircealungu commented on wordstats/edit_distance_overlap.py
> +class WordDistanceOverlap(WordDistanceFactory):
comment on what exactly this is would be very welcome!

2018-05-23 09:37 UTC, mircealungu reviewed
see the comments.
also, i'll send you in a bit a pull request to your branch, with a few restructurings.

2018-05-23 09:37 UTC, mircealungu commented on wordstats/cognate_automatic_evaluation.py
> +from wordstats.cognate_info import CognateInfo
comment at the top of the file specifying what it's doing.

2018-05-23 09:37 UTC, mircealungu commented on wordstats/cognate_automatic_evaluation.py
> +#cognateInfo.whitelist.clear()
remove commented out code.

2018-05-23 09:37 UTC, mircealungu commented on wordstats/cognate_automatic_evaluation.py
> +from python_translators.translators.glosbe_over_tor_translator import GlosbeOverTorTranslator
so is this GlosbeOverTor working after all? 
or is this code not used anymore?

2018-05-23 09:37 UTC, mircealungu commented on wordstats/cognate_files_path.py
> +    return path_to_cognate_file(primary, secundary, CANDIDATES, method_name)
secondary not secundary.
here and hereafter.

2018-05-23 09:37 UTC, mircealungu commented on wordstats/cognate_files_path.py
> +def path_to_cognate_file(primary, secundary, file_name, method_name = ""):
this method is private to this file (or module in Python). 
the convention is to prefix it's name with an underscore: `_ path_to_cognate_file`.

2018-05-23 09:37 UTC, mircealungu commented on wordstats/cognate_files_path.py
> +def load_from_path(path):
truth is, this file could be split in two: 
- cognate_paths
- file_operations

and moved to it's own module: file_handling probably.

2018-05-23 09:37 UTC, mircealungu commented on wordstats/edit_distance_translate.py
> +from googletrans import Translator
what's this googletrans thing? 
it's not in the required packages in setup.py.

2018-05-23 09:37 UTC, mircealungu commented on wordstats/cognate_info.py
> +    # def apply_distance_metric(self, wordlist1, wordlist2, func):
what's this? 
is it a comment for a commented out function? 
remove both.

2018-05-23 09:37 UTC, mircealungu commented on wordstats/cognate_info.py
> +    def compute_translator(self, translator:Translator, save:Boolean = False):
this is not a self-explanatory name.
think of a better name, and also add docstring.

2018-05-23 09:37 UTC, mircealungu commented on wordstats/edit_distance.py
> +        # these might change based on the primary secondayr
secondayr

2018-05-23 09:37 UTC, mircealungu commented on wordstats/edit_distance.py
> +        lengthLongest = max(len(word1),len(word2))
length_longest

2018-05-23 09:37 UTC, mircealungu commented on wordstats/edit_distance_translate.py
> +class WordDistanceOverlap(WordDistanceFactory):
`WordDistanceOverlap`, a kind of `WordDistance`, can't be the subclass of a `WordDistanceFactory`. 
This makes me think that your superclass should be actually named `WordDistance`. 
Would that make sense to you?

2018-06-07 15:06 UTC, joelgrondman commented
I've merged the branches together, restructurings are applied as well as the renames.

2018-06-19 09:44 UTC, closed without merging

2018-06-19 09:44 UTC, mircealungu commented
waiting for a smaller PR :)